version: '3.8'

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    networks:
      - docker-pod
    ports:
      - "80:80"
      - "443:443"
#      - "81:81"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"  # Safe SQLite file location
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
      - npm_logs:/data/logs   # Separate volume for logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:81/login"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  docker-pod:
    external: true

volumes:
  npm_data:
  npm_letsencrypt:
  npm_logs:
