version: '3.8'

services:
  nextcloud-db:
    image: postgres:16
    container_name: nextcloud-db
    restart: always
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextclouduser
      POSTGRES_PASSWORD: nextcloudpass
    volumes:
      - nextcloud-db:/var/lib/postgresql/data
    networks:
      - nextcloud-net
    shm_size: 1g  # Better performance for PostgreSQL

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always
    networks:
      - nextcloud-net

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud-app
    restart: always
    ports:
      - 8080:80
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextclouduser
      POSTGRES_PASSWORD: nextcloudpass
      POSTGRES_HOST: nextcloud-db
      REDIS_HOST: redis
    volumes:
      - nextcloud-html:/var/www/html
    depends_on:
      - nextcloud-db
      - redis
    networks:
      - nextcloud-net

  cron:
    image: nextcloud:latest
    container_name: nextcloud-cron
    restart: always
    entrypoint: /cron.sh
    volumes:
      - nextcloud-html:/var/www/html
    depends_on:
      - nextcloud-db
    networks:
      - nextcloud-net

volumes:
  nextcloud-db:
  nextcloud-html:

networks:
  nextcloud-net:
    driver: bridge
